###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Jorge Salgado",
  "items": 0
}

###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "name": "Jorge Salgado",
  "items": 0
}